id: I6082EF0B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-18T10:21:38+00:00'
last_modified: '2022-06-08T04:11:57.109776+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4244
  title: རྒྱ་གཞུང་སྐོར་གྱི་ཚད་མ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8CAD:
      image_group_id: I1KG4956
      title: Volume 1 of rgya gzhung skor gyi tshad ma phyogs bsgrigs/
      total_pages: 472
      order: 1
      base_file: 8CAD.txt
    C8E8:
      image_group_id: I1KG4957
      title: Volume 2 of rgya gzhung skor gyi tshad ma phyogs bsgrigs/
      total_pages: 452
      order: 2
      base_file: C8E8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
